name: Assignment 3 - Build, Test, and Query

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create log file
        run: |
          echo "$(date -Iminutes)" > log.txt
          echo "User's Build" >> log.txt

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker compose -f docker-compose.yml build
        working-directory: .

      - name: Log image build result
        if: success()
        run: echo "Image successfully built" >> log.txt
        else:
          run: echo "Image build failed" >> log.txt

      - name: Upload Docker image as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: ./books-service

      - name: Upload build log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: log.txt

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Docker image
        run: docker load < docker-image.tar

      - name: Start services with Docker Compose
        run: docker compose -f docker-compose.yml up -d
        working-directory: .

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests

      - name: Run tests
        run: pytest -v ./books-service/tests/assn3_tests.py > assn3_test_results.txt

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: assn3_test_results.txt

  query:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Start services with Docker Compose
        run: docker compose -f docker-compose.yml up -d
        working-directory: .

      - name: Execute Queries
        run: |
          # Example of running a curl command to POST data
          curl --location --request POST 'http://127.0.0.1:5001/books' -H "Content-Type: application/json" -d '{"title": "New Book", "ISBN": "1234567890123", "genre": "Fiction"}'
          # Example of running a curl command to GET data
          curl --location --request GET 'http://127.0.0.1:5001/books?genre=Fiction'

      - name: Shut down Docker Compose
        run: docker compose down
